### ISSUE TITLE
Training and Testing paradigm

### ISSUE THREAD

**Issue by abhishekaich27** [Haotianz94/IL_video_inpainting#4]
Hi,

1. **(EDIT: This query is clear to me now. )** Could you, in simple words, kindly explain the training and testing parts of the proposed methodology? 

2. How do you generate the whole impainted video in the end? I see that that the generator produces a single image at a time. 

Pardon me if the questions are naive, but I just wanted to be sure of my understanding. Also, thank you for making your implementation available!

**Comment by Haotianz94** [comment]
Sorry for the late reply due to a recent submission. For 2. the model (generator) is trained over the whole video. Once training is done, we use the model to squentially generate each frame by taking input the corresponding noise map.
